name = "dLdL"
license = "MIT"
licenselink = "https://github.com/dldl/dldl.io/blob/master/LICENSE.md"
description = ""
homepage = "https://dldl.io"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = ""
  homepage = ""

